version: "3.4"

services:
  php:
    container_name: eoffice.php
    build:
      context: ./
      target: eoffice_php
    depends_on:
      - database
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    networks:
      - eoffice

  pwa:
    container_name: eoffice.pwa
    build:
      context: ./
      target: eoffice_pwa_prod
      dockerfile: ./assets/Dockerfile
    environment:
      API_PLATFORM_CLIENT_GENERATOR_ENTRYPOINT: http://caddy
      NEXT_PUBLIC_ENTRYPOINT: http://caddy
    volumes:
      - ./package.json:/usr/src/pwa/package.json
    networks:
      - eoffice

  caddy:
    container_name: eoffice.caddy
    build:
      context: ./
      target: eoffice_caddy
    depends_on:
      - php
      #- pwa
    environment:
      PWA_UPSTREAM: pwa:3000
      SERVER_NAME: ${SERVER_NAME:-localhost, caddy:80}
      MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_PUBLISHER_JWT_KEY:-!ChangeMe!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_SUBSCRIBER_JWT_KEY:-!ChangeMe!}
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
      - caddy_data:/data
      - caddy_config:/config
    ports:
      # HTTP
      - target: 80
        published: 80
        protocol: tcp
      # HTTPS
      - target: 443
        published: 443
        protocol: tcp
      # HTTP/3
      - target: 443
        published: 443
        protocol: udp
    networks:
      - eoffice

  database:
    container_name: eoffice.database
    image: 'mariadb:10'
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
      - target: 3306
        published: 3306
        protocol: udp
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'db_data:/var/lib/mysql:rw'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s
    networks:
      - eoffice

  phpmyadmin:
    container_name: eoffice.phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - eoffice
  chrome:
    container_name: "eoffice.chrome"
    image: selenium/standalone-chrome
    network_mode: host
    
volumes:
  php_socket:
  db_data:
  caddy_data:
  caddy_config:

networks:
  eoffice:
    driver: bridge
