version: "3.4"

services:
  php:
    container_name: eoffice.php
    build:
      context: ./api
      target: eoffice_php
    depends_on:
      - database
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s

  pwa:
    container_name: eoffice.pwa
    build:
      context: ./pwa
      target: eoffice_pwa_prod
    environment:
      API_PLATFORM_CLIENT_GENERATOR_ENTRYPOINT: http://caddy
      NEXT_PUBLIC_ENTRYPOINT: http://caddy

  caddy:
    container_name: eoffice.caddy
    build:
      context: ./api
      target: eoffice_caddy
    depends_on:
      - php
      - pwa
    environment:
      PWA_UPSTREAM: pwa:8080
      SERVER_NAME: ${SERVER_NAME:-localhost, caddy:80}
      MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_PUBLISHER_JWT_KEY:-!ChangeMe!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_SUBSCRIBER_JWT_KEY:-!ChangeMe!}
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
      - caddy_data:/data
      - caddy_config:/config
    ports:
      # HTTP
      - target: 80
        published: 80
        protocol: tcp
      # HTTPS
      - target: 443
        published: 443
        protocol: tcp
      # HTTP/3
      - target: 443
        published: 443
        protocol: udp

  database:
    container_name: eoffice.database
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=eoffice
      - POSTGRES_PASSWORD=eoffice
      - POSTGRES_USER=eoffice
    volumes:
      - ./var/db/data:/var/lib/postgresql/data:rw
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./api/docker/db/data:/var/lib/postgresql/data:rw

  chrome:
    container_name: "eoffice.chrome"
    image: selenium/standalone-chrome:2.44.0
    network_mode: host
    privileged: true
    shm_size: 2g
    #ports:
    #  - '5900:5900'
    #  - '4444:4444'
  #  environment:
  #    - JAVA_OPTS=-Dwebdriver.chrome.whitelistedIps=
  #  shm_size: 2g
  #  privileged: true

volumes:
  php_socket:
  caddy_data:
  caddy_config: