<?php

namespace Functional\EOffice\User;

use ApiPlatform\Core\Bridge\Symfony\Bundle\Test\Client;
use EOffice\Testing\ApiTestCase;
use EOffice\Testing\Concerns\InteractsWithORM;
use EOffice\User\Testing\InteractsWithUser;
use Hautelook\AliceBundle\PhpUnit\RefreshDatabaseTrait;

/**
 * @covers \EOffice\User\UserModule
 */
class SecurityApiTest extends ApiTestCase
{
    use InteractsWithUser, RefreshDatabaseTrait;

    private Client $client;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->client = static::createClient();
    }

    public function test_it_should_handle_user_login(): void
    {
        $client = $this->client;
        $this->iHaveUser();
        $client->request('POST', '/login', ['json' =>[
            'username' => 'test',
            'password' => 'test'
        ]]);

        $this->assertResponseIsSuccessful();
    }
}
