<?php

namespace Functional\EOffice\User;

use ApiPlatform\Core\Bridge\Symfony\Bundle\Test\ApiTestCase;
use EOffice\Testing\Concerns\InteractsWithORM;
use EOffice\Testing\FunctionalTestCase;
use EOffice\User\Testing\InteractsWithUser;
use Hautelook\AliceBundle\PhpUnit\RefreshDatabaseTrait;

/**
 * @covers \EOffice\User\Model\User
 * @covers \EOffice\User\UserModule
 */
class UserApiTest extends ApiTestCase
{
    use InteractsWithORM, InteractsWithUser, RefreshDatabaseTrait;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->client = static::createClient();
    }

    public function test_create_user()
    {
        $response = $this->client->request('POST', '/api/users', ["json" =>
            [
                'username' => 'test',
                'email' => 'test@example.org',
                'plainPassword' => 'test',
            ]
        ]);

        $this->assertResponseIsSuccessful();
        $this->assertResponseHeaderSame('content-type', 'application/ld+json; charset=utf-8');
        $this->assertJsonContains(['username' => 'test']);

        $json = $response->toArray();
        $this->assertArrayNotHasKey('password', $json);
        $this->assertArrayNotHasKey('plainPassword', $json);
        //$this->assertSame('foo', $response->toArray());
    }
}
