security:
    enable_authenticator_manager: true
    providers:
        api_user_provider:
            entity:
                class: EOffice\Contracts\User\Model\UserInterface
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: api_user_provider
            json_login:
                check_path: /login
            switch_user: true
    password_hashers:
        EOffice\Contracts\User\Model\UserInterface:
            algorithm: bcrypt
    access_control:
        - { path: ^/api/users, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: ROLE_USER }
