security:
    enable_authenticator_manager: true
    providers:
        api_user_provider:
            entity:
                class: EOffice\Contracts\User\Model\UserInterface
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            stateless: true
            provider: api_user_provider
            json_login:
                check_path: /api/login
                username_path: username
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            switch_user: true
    password_hashers:
        EOffice\Contracts\User\Model\UserInterface:
            algorithm: bcrypt
    access_control:
        - { path: ^/api/users, roles: PUBLIC_ACCESS }
        - { path: ^/api/login, roles: PUBLIC_ACCESS}
        - { path: ^/api, roles: ROLE_USER }
