services:
    _defaults:
        autowire: true
        autoconfigure: true

    Integration\EOffice\DemoContext:
        public: true
        autoconfigure: true
        tags:
            name: container.service_subscriber
